services:
  db:
    image: postgres:12
    container_name: intralaser-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: intralaser
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./dump-intralaser-dev-202504280958-plain.sql:/docker-entrypoint-initdb.d/dump-intralaser-dev-202504280958-plain.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: intralaser-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  db_data:
